sudo: required
services:
    - docker


before_install:
    - docker build -t sandeepdamacharla/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true sandeepdamacharla/frontend npm run test



